apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: apps.cross-cluster.crossplane.io
spec:
  group: cross-cluster.crossplane.io
  names:
    kind: App
    plural: apps
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
                description: Region that the app will be deployed in.
                enum:
                - west
                - east
            required:
            - region
