apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: cross-cluster
spec:
  crossplane:
    version: ">=v1.0.0-0"
  dependsOn:
    - provider: crossplane/provider-gcp
      version: ">=v0.15.0-0"
    - provider: crossplane/provider-helm
      version: ">=v0.5.0-0"
